### ISSUE TITLE
Unhelpful exception error messages, e.g. "TypeError: 8" when calling function on custom object

### ISSUE THREAD

**Issue by axefrog** [fholm/IronJS#81] opened 2011-07-16 18:47 UTC
Would love to see exceptions thrown by the runtime updated so they have helpful messages. This would make it a lot easier to figure out why they have been thrown without needing a deep understanding of IronJS' internals.

Using the wiki article [Create a custom javascript object](https://github.com/fholm/IronJS/wiki/Create-a-custom-javascript-object), I created my first custom object for use my with my JavaScript context. Construction of the object worked fine, but when I called the method `LoadURL` on my object, the following exception was thrown:

> Exception thrown: IronJS.UserError: TypeError: 8
>   at IronJS.Hosting.FSharp.run(Delegate compiled, T t) in C:\Users\otac0n\Projects\IronJS\Src\IronJS\Hosting.fs:line 151
>   at IronJS.Hosting.CSharp.Context.Execute(String source) in C:\Users\otac0n\Projects\IronJS\Src\IronJS\Hosting.fs:line 240
>   at ...

Debugging eventually revealed that it was my fault - I messed up the casing when calling my custom object's only function, but this took me a while to realise due to the obscure error message.

**Comment by otac0n** [comment] 2011-07-16 19:17
This is a duplicate of: https://github.com/fholm/IronJS/issues/50
I'm going to close this as such.

Would you mind posting this on that issue?  We appreciate your feedback, but we don't want duplicate bug reports floating around.

Thanks!

**Closed as completed by otac0n** 2011-07-16 19:17 UTC
Labels: Duplicate

**Comment by axefrog** [comment] 2011-07-16 19:18
Whoops, sorry didn't see that one.
